# Generated by Django 5.0.6 on 2024-08-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_published_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
